---
- hosts: network-nodes
  gather_facts: no

  tasks:

    - name: copy public part of key
      copy: src=~/.ssh/id_rsa.pub dest=/home/vagrant/id_rsa.pub owner=vagrant mode=755 force=yes

    - name: append key to authorized keys
      shell: cat /home/vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
