---
- hosts: network-nodes
  gather_facts: yes
#  become: yes

  tasks:

    - name: Ensures scripts dir exists
      file: path=/home/{{username}}/scripts state=directory

    - name: copy python sender file to send packets
      copy: src=../../scripts/ dest=/home/{{username}}/scripts

#    - name: install the latest version of tcpdump
#      apt: name=tcpdump state=latest

